---
- name: 'Check mandatory variables are defined'
  assert:
    that:
      - downloads_dir is defined
      - stroom_proxy_archive_filename is defined
      - stroom_proxy_install_root_dir is defined
      - stroom_proxy_url is defined
      - stroom_proxy_archive_checksum_type is defined
      - stroom_proxy_archive_checksum_url is defined
  tags:
    - proxy

- debug:
    msg:
      - "downloads_dir: {{ downloads_dir }}"
      - "stroom_proxy_archive_filename: {{ stroom_proxy_archive_filename }}"
      - "stroom_proxy_url: {{ stroom_proxy_url }}"
    verbosity: 2
  tags:
    -- proxy

- name: "See if {{ stroom_proxy_home_dir }} exists"
  stat:
    path: "{{ stroom_proxy_home_dir }}"
  register: _stroom_proxy_home_dir_info
  tags:
    - proxy

- name: Ensure directories exists
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - "{{ downloads_dir }}"
    - "{{ stroom_proxy_home_dir }}/config"
    - "{{ stroom_proxy_home_dir }}"
    - "{{ stroom_proxy_certs_dir }}"
    - "{{ stroom_proxy_content_dir }}"
    - "{{ stroom_proxy_logs_dir }}"
    - "{{ stroom_proxy_repo_dir }}"
    - "{{ stroom_proxy_install_root_dir }}/stroom-proxy/{{ stroom_proxy_version }}"
  tags:
    - proxy
    - configure
    - deploy

- name: Download stroom-proxy distribution {{ stroom_proxy_url }}
  get_url:
    url: "{{ stroom_proxy_url }}"
    dest: "{{ downloads_dir }}/{{ stroom_proxy_archive_filename }}"
    checksum: "{{ stroom_proxy_archive_checksum_type }}:{{ stroom_proxy_archive_checksum_url }}"
    timeout: 120

- name: Unpack Stroom-proxy's distribution zip
  unarchive:
    src: "{{ downloads_dir }}/{{ stroom_proxy_archive_filename }}"
    dest:  "{{ stroom_proxy_install_root_dir }}/stroom-proxy/{{ stroom_proxy_version }}"
    remote_src: true
  tags:
    - proxy


- name: Create a symlink for 'latest'
  file:
    state: link
    force: true
    src: "{{ stroom_proxy_install_root_dir }}/stroom-proxy/{{ stroom_proxy_version }}"
    dest: "{{ stroom_proxy_install_root_dir }}/stroom-proxy/latest"
  tags:
    - proxy
    - deploy
    - configure


- name: Find downloaded config files on remote machine
  find:
    paths: "{{ stroom_proxy_install_root_dir }}/stroom-proxy/{{ stroom_proxy_version }}/config"
  register: existing_config

- name: Copy config from distro into {{ stroom_proxy_home_dir }}/config
  copy:
    src: "{{ item.path }}"
    dest: "{{ stroom_proxy_home_dir }}/config/{{ item.path | basename }}"
    mode: "u=rw,g=,o="
    backup: false
    remote_src: true
  with_items: "{{ existing_config.files }}"
  tags:
    - deploy
    - configure
    - proxy

- name: Remove downloaded config dir and its contents
  file:
    state: absent
    path: "{{ stroom_proxy_install_root_dir }}/stroom-proxy/{{ stroom_proxy_version }}/config"

- name: Replace downloaded config with symlink
  file:
    state: link
    force: true
    src: "{{ stroom_proxy_home_dir }}/config"
    dest: "{{ stroom_proxy_install_root_dir }}/stroom-proxy/{{ stroom_proxy_version }}/config"
  tags:
    - deploy
    - configure
    - proxy