Vagrant.configure("2") do |config|

  @ip_counter=10

  def get_ip()
    @ip_counter += 1
    "192.168.101.#{@ip_counter}"
  end

  # TODO Only allows a host to belong to one group, but that should
  # be fine for now.
  servers=[
    {
      :hostname => "stroom-remote-proxy-stack",
      :ip => get_ip(),
      :group => "stroom_remote_proxy_stack"
    },
  ]

  servers.each do |machine|
    config.vm.define machine[:hostname] do |node|
      node.vm.box = "centos/7"
      node.vm.hostname = machine[:hostname]
      node.vm.network "private_network", ip: machine[:ip]

      node.vm.provider "virtualbox" do |vb|
        vb.memory = "3096"
        vb.cpus = "2"
      end

    end
  end

  config.vm.provision "ansible" do |ansible|
    ansible.verbose = "v"
    # Noddy playbook that doesn't change anything just so we can generate an inventory
    ansible.playbook = "vagrant_playbook.yml"

    # TODO Figure out how to get rid of those pesky cows

    # Add each machine to the appropriate ansible group
    ansible.groups = { }
    $stdout.puts "Ansible hosts:"
    servers.each do |machine|
      group = machine[:group]
      hostname = machine[:hostname]
      $stdout.puts "  hostname: #{hostname}, ip: #{machine[:ip]}, group: #{group}"

      if !ansible.groups.key?(group)
        # No key for this group so create an empty array
        ansible.groups[group] = []
      end
      # Add this host to the group
      ansible.groups[group].push(hostname)
    end

    $stdout.puts "Ansible groups:"
    ansible.groups.each_pair do |key,value|
      $stdout.puts "  #{key}: #{value}"
    end
  end
end

# vim: set tabstop=2 shiftwidth=2 expandtab filetype=ruby:
