---

- name: 'Check mandatory variables are defined'
  assert:
    that:
      - stroom_user is defined
      - stack_name is defined
      - stack_version is defined
      - stack_install_root_dir is defined


- name: SystemD Service File
  vars:
    stack_dir: "{{ stack_install_root_dir }}/{{ stack_name }}/{{ stack_name }}-{{stack_version }}"
  template:
    src: "templates/etc/systemd/system/stroom.service.j2"
    dest: "/etc/systemd/system/stroom.service"
