---
- name: Setup all hosts, installing dependencies such as docker
  hosts: stroom_database
  vars_files:
    - ./variables.yml
    - ../global_variables.yml
    - ../config/user_settings.yml
  roles:
    - roles/setup/mysql

- name: Open port for MySQL
  become: true
  firewalld:
    port: "{{ mysql_port }}/tcp"
    zone: public
    permanent: true
    state: enabled
