---
- name: Setup all hosts with common packages, and a yum update
  hosts: all
  gather_facts: true
  tags:
    - common
  tasks:
    - import_role:
        name: roles/setup/common


- name: Setup hosts with docker and docker-compose
  become: true
  hosts:
    - ~.*_stack$
    - stroom_db_migration
  vars:
    docker_user: "{{ stroom_user }}"
  tags:
    - install_docker
  tasks:

    - import_role:
        name: roles/setup/docker

      # TODO The ports we need are dependant on what is in the stack
      # so we ought to only open the required ports
      # TODO Assumes the public zone is in use
    - name: Opening TCP port to public zone in firewalld
      when: no_firewalld is undefined
      firewalld:
        port: "{{ item }}/tcp"
        zone: public
        permanent: true
        immediate: true
        state: enabled
      loop:
        - "{{ stroom_app_port | default(8080) }}"
        - "{{ stroom_proxy_local_app_port | default(8090) }}"
        - "{{ stroom_auth_service_app_port | default(8099) }}"
        - "{{ stroom_proxy_remote_app_port | default(9090) }}"
        - "{{ stroom_auth_ui_https_port | default(9443) }}"
      notify:
        - Restart docker
        
    - name: Opening mySQL stack TCP port to public zone in firewalld
      when: no_firewalld is undefined
      firewalld:
        port: "{{ item }}/tcp"
        zone: public
        permanent: true
        immediate: true
        state: enabled
      loop:
        - "{{ stroom_all_dbs_port | default(3307) }}"
      notify:
        - Restart docker
      when: 
        - mixed_cluster == 'false' or   mixed_cluster is not defined      # is false or not defined

    - name: Opening mySQL cluster Stroom DB TCP port to public zone in firewalld
      when: no_firewalld is undefined
      firewalld:
        port: "{{ item }}/tcp"
        zone: public
        permanent: true
        immediate: true
        state: enabled
      loop:
        - "{{ stroom_db_port | default(3306) }}"
      notify:
        - Restart docker
      when: 
        - mixed_cluster is defined
        - mixed_cluster == 'true' # is true

      # TODO The ports we need are dependant on what is in the stack
      # so we ought to only open the required ports
      # TODO Assumes the public zone is in use
    - name: Opening services to public zone in firewalld
      when: no_firewalld is undefined
      firewalld:
        service: "{{ item }}"
        zone: public
        permanent: true
        immediate: true
        state: enabled
      loop:
        - http # For nginx
        - https # For nginx
      notify:
        - Restart docker

  handlers:
    - name: Restart docker
      service: 
        name: docker 
        state: restarted


- name: Setup hosts with java
  become: true
  hosts:
    - stroom
    - stroom_ui
    - stroom_with_proxy
    - stroom_and_proxy
    - stroom_proxy
  vars:
    # Set java_version based on the stroom version
    # TODO Seeing InaccessibleObjectException when running j16 unless jvm arg --illegal-access=permit is used, so setting at j15 for now.
    java_version: '{{ 8 if stroom_version is search("^v6\.") else 17 if stroom_version is search("^v7\.2") else 15 }}'
  tags:
    - install_java
  tasks:

    - import_role:
        name: roles/setup/java

    - name: Opening TCP port to public zone
      when: no_firewalld is undefined
      firewalld:
        port: "{{ item }}/tcp"
        zone: public
        permanent: true
        immediate: true
        state: enabled
      loop:
        - "{{ stroom_app_port | default(8080) }}"
        - "{{ stroom_proxy_app_port | default(8090) }}"

- name: Setup hosts with mysql
  become: true
  hosts:
    - stroom_database
    - stroom_stats_database
  tags:
    - install_mysql
  tasks:

    - import_role:
        name: roles/setup/mysql

    - name: Open port for MySQL
      when: no_firewalld is undefined
      firewalld:
        port: "{{ mysql_port }}/tcp" # Was  service: mysql
        zone: public
        permanent: true
        immediate: true
        state: enabled
