---

- name: 'Check mandatory variables are defined'
  assert:
    that:
      - downloads_dir is defined
      - stroom_archive_filename is defined
      - stroom_install_root_dir is defined
      - stroom_url is defined

- debug:
    msg:
      - "downloads_dir: {{ downloads_dir }}"
      - "stroom_archive_filename: {{ stroom_archive_filename }}"
      - "stroom_url: {{ stroom_url }}"
    verbosity: 2

- name: "See if {{ stroom_home_dir }} exists"
  stat:
    path: "{{ stroom_home_dir }}"
  register: _stroom_home_dir_info

- name: "Download archive {{ _stroom_stack_archive_url }}" 
  when: _stroom_home_dir_info.stat.exists == false
  block:

    - name: Ensure directory {{ downloads_dir }} exists
      file:
        path: "{{ downloads_dir }}"
        state: directory

    - name: Download stroom distribution {{ stroom_url }}
      when: stroom_url is match("http.*")
      get_url:
        url: "{{ stroom_url }}"
        dest: "{{ downloads_dir }}/{{ stroom_archive_filename }}"
        checksum: "sha256:{{ stroom_url }}.sha256"
        timeout: 120

    - name: Download stroom distribution from S3 {{ stroom_url }}
      when: stroom_url is match("s3://.*")
      amazon.aws.s3_object:
        bucket: "{{ stroom_url.split('/').2 }}"
        object: "{{ stroom_url | regex_replace('s3://[^/]+/') }}"
        dest: "{{ downloads_dir }}/{{ stroom_archive_filename }}"
        mode: get

    - name: Ensure install directory {{ stroom_home_dir }} exists
      file:
        path: "{{ stroom_home_dir }}"
        state: directory

    - name: Unpack Stroom's distribution zip
      unarchive:
        src: "{{ downloads_dir }}/{{ stroom_archive_filename }}"
        dest:  "{{ stroom_home_dir }}"
        remote_src: true

    - name: Ensure logs directory exists
      file:
        path:  "{{ stroom_app_home_dir | default(stroom_home_dir) }}/logs"
        state: directory

######## END OF BLOCK ######## 


- name: Create a symlink for 'latest'
  file:
    state: link
    force: true
    src: "{{ stroom_version }}"
    dest: "{{ stroom_install_root_dir }}/stroom/latest"


