---
- name: 'Check mandatory variables are defined'
  assert:
    that:
      - stack_install_root_dir is defined
      - stack_version is defined
      - stack_name is defined

- name: Reset the active services to the defaults by deleting ACTIVE_SERVICES.txt
  file: 
    path: "{{ stack_install_root_dir }}/{{ stack_name }}/{{ stack_name }}-{{ stack_version }}/ACTIVE_SERVICES.txt"
    state: absent
