---

- name: 'Check mandatory variables are defined'
  assert:
    that:
      - stroom_user is defined
      - stroom_version is defined
      - stroom_home_dir is defined
      - stroom_service_on_boot is defined
      - stroom_service_state is defined

- name: SystemD Service File
  become: true
#  vars:
#    stroom_version:  "{{ stroom_version }}"
#    stroom_home_dir: "{{ stroom_home_dir }}"
  template:
    src: "templates/etc/systemd/system/stroom.service.j2"
    dest: "/etc/systemd/system/stroom.service"

- name: SystemD Service enable
  when: stroom_service_on_boot is defined
  become: true
  systemd:
    name: stroom
    enabled: "{{ stroom_service_on_boot }}"

- name: SystemD Service start
  when: stroom_service_state is defined
  become: true
  systemd:
    name: stroom
    state: "{{ stroom_service_state }}"
