---

- name: Stop Stroom Service
#  listen: Reload Stroom Service
  become: true
  become_user: root
  systemd:
    name: stroom
    state: stopped

- name: Reload systemd Daemon
#  listen: Reload Stroom Service
  become: true
  become_user: root
  systemd:
    daemon_reload: true
