---

- name: 'Check mandatory variables are defined'
  assert:
    that:
      - stroom_user is defined
      - stroom_proxy_version is defined
      - stroom_proxy_home_dir is defined
      - stroom_service_on_boot is defined
      - stroom_service_state is defined
      - java_version is defined

- name: SystemD Service File
  become: true
  become_user: root
#  vars:
#    stroom_proxy_version:  "{{ stroom_proxy_version }}"
#    stroom_proxy_home_dir: "{{ stroom_proxy_home_dir }}"
  template:
    src: "templates/etc/systemd/system/stroom-proxy.service.j2"
    dest: "/etc/systemd/system/stroom-proxy.service"
  notify:
    - Stop Stroom Proxy Service
    - Reload systemd Daemon

# Force the old service to stop prior to starting the new one
- name: Flush handlers
  meta: flush_handlers

- name: SystemD Service start/enable
  when: stroom_service_state is defined
  become: true
  become_user: root
  systemd:
    name: stroom-proxy
    state: "{{ stroom_service_state }}"
    enabled: "{{ stroom_service_on_boot }}"

