---
stack_version_base_dir: "{{ stack_install_root_dir }}/{{ stack_name }}/{{ stack_version }}"
stack_bin_dir: "{{ stack_version_base_dir }}/bin"
stack_config_dir: "{{ stack_bin_dir }}/config"
stack_volumes_dir: "{{ stack_version_base_dir }}/volumes"

stack_env_var_file: "{{ stack_config_dir }}/{{ stack_name }}.env"
stack_env_vars: {}
