---
- name: "Do a YUM update on all installed packages"
  become: true
  yum:
    name: "*"
    state: latest
  tags:
    - never # Task won't run unless one of the other tags is set
    - yum_update
  register: yum_update_info

# The next three tasks will ONLY run if you supply the allow_reboot tag
- name: restart system to reboot to newest kernel
  become: true
  shell: "sleep 5 && reboot"
  async: 1
  poll: 0
  tags:
    - never
    - allow_reboot
  when: yum_update_info.changed
  register: reboot_info

- name: wait for 10 seconds
  pause:
    seconds: 10
  tags:
    - never
    - allow_reboot
  when: reboot_info.changed

- name: wait for the system to reboot
  wait_for_connection:
    connect_timeout: 20
    sleep: 3
    delay: 0
    timeout: 120
  tags:
    - never
    - allow_reboot
  when: reboot_info.changed
